language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t hchsia/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true hchsia/docker-react npm run test

deploy:
    provider: elasticbeanstalk
    region: "ap-northeast-1"
    app: "docker"
    env: "Docker-env"
    bucket_name: "elasticbeanstalk-ap-northeast-1-023519552748"
    bucket_path: "docker"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key:
        secure: "$AWS_SECRET_KEY"
        